// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP04zT1LjWXNtkx9yUqSnzAC360NMqHPs',
    appId: '1:513118252967:web:5cbe1845c6173118fb5082',
    messagingSenderId: '513118252967',
    projectId: 'alca-a91d7',
    authDomain: 'alca-a91d7.firebaseapp.com',
    storageBucket: 'alca-a91d7.appspot.com',
    measurementId: 'G-BNTNXBPS2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXuxplBkt5oP3mpesGv1tBMtRk8StBUXo',
    appId: '1:513118252967:android:c37d5b54b762f0dbfb5082',
    messagingSenderId: '513118252967',
    projectId: 'alca-a91d7',
    storageBucket: 'alca-a91d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb74nCeIzC4tbnaO4E0xNgj6r6hcw81Tc',
    appId: '1:513118252967:ios:39ad0829c16ae2c8fb5082',
    messagingSenderId: '513118252967',
    projectId: 'alca-a91d7',
    storageBucket: 'alca-a91d7.appspot.com',
    iosBundleId: 'com.example.gpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb74nCeIzC4tbnaO4E0xNgj6r6hcw81Tc',
    appId: '1:513118252967:ios:39ad0829c16ae2c8fb5082',
    messagingSenderId: '513118252967',
    projectId: 'alca-a91d7',
    storageBucket: 'alca-a91d7.appspot.com',
    iosBundleId: 'com.example.gpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP04zT1LjWXNtkx9yUqSnzAC360NMqHPs',
    appId: '1:513118252967:web:5ea63d316f51d617fb5082',
    messagingSenderId: '513118252967',
    projectId: 'alca-a91d7',
    authDomain: 'alca-a91d7.firebaseapp.com',
    storageBucket: 'alca-a91d7.appspot.com',
    measurementId: 'G-X4GVYWP863',
  );
}
